### ISSUE TITLE
Wireshark extcap

### ISSUE THREAD

**Issue by desowin** [matwey/libopenvizsla#1]
This library is pretty much excellent choice for Wireshark extcap for OpenVizsla. I think so, because it should be possible to just compile a single executable that could simply be copied to Wireshark extcap directory.

As for actual options, I think we could have capture speed (low/full/high) and potentially FPGA firmware selection (use preloaded one, or a file selected by user).

**Comment by matwey** [comment]
Hi,

Why do we need extcap if we could add implementation to libpcap?
Anyway, I think it is a good idea to have an binary tool demonstrating this library usage. Wireshark extcap is a good goal for such a tool.

**Comment by desowin** [comment]
> Why do we need extcap if we could add implementation to libpcap?

On Linux this is hassle free, but on Windows it is not so straight forward. With extcap we could have a single exe file to be copied to Wireshark extcap directory - and instructions that user should install libusb supported drivers for OpenVizsla VID/PID.

**Comment by matwey** [comment]
Now I see. But I have never tried to build the library for Windows :-)
Frankly speaking, it is in a long perspective. There has been no interest in the library until then, so I was not quite active on it. So, I planned to finish it for Linux first.

**Comment by matwey** [comment]
@desowin do you think that we can close it now?

**Comment by desowin** [comment]
> @desowin do you think that we can close it now?

Yes, it can be closed. It would be best if there was exe (possibly static linked) available for tagged releases.

**Comment by matwey** [comment]
I can ask Appveyor CI to upload build artifacts to GitHub Releases. I am not sure about is it possible to link with libftdi and libzip statically.

**Comment by desowin** [comment]
> I can ask Appveyor CI to upload build artifacts to GitHub Releases. I am not sure about is it possible to link with libftdi and libzip statically.

Static linking to Open Source libraries on Windows is generally much simplier in vcpkg than with MingGW. I didn't manage to get openvizsla vcpkg port - have you worked on it?

**Comment by matwey** [comment]
No, I only handled issues in the dependencies ports.
Frankly speaking, it would be great if you could handle vcpkg port, because I am not native windows user.

**Comment by desowin** [comment]
I can see that you uploaded precompiled 0.1.0 binaries for Windows but it only includes the library. Can you make it to also include the ovextcap binary?

**Comment by matwey** [comment]
I didn't do anything special. I'll look how to ask `CMake` to put `ovextcap` to the archive.

**Comment by matwey** [comment]
Could you please test if this works?
[libopenvizsla-0.1.0-win64.zip](https://github.com/matwey/libopenvizsla/files/6524476/libopenvizsla-0.1.0-win64.zip)

**Comment by desowin** [comment]
> Could you please test if this works?
> [libopenvizsla-0.1.0-win64.zip](https://github.com/matwey/libopenvizsla/files/6524476/libopenvizsla-0.1.0-win64.zip)

The code execution cannot proceed because getopt.dll was not found. Reinstalling the program may fix this problem. 
The code execution cannot proceed because openvizsla.dll was not found. Reinstalling the program may fix this problem.

**Comment by desowin** [comment]
And if I copy openvizsla.dll, then I get a bunch of more missing dlls:

The code execution cannot proceed because libusb-1.0.dll was not found. Reinstalling the program may fix this problem. 
The code execution cannot proceed because zip.dll was not found. Reinstalling the program may fix this problem. 
The code execution cannot proceed because ftdi1.dll was not found. Reinstalling the program may fix this problem. 

If possible, a static build would bring least hassle.

**Comment by matwey** [comment]
@desowin 
Could you please check if the following artifacts work for you?
https://github.com/matwey/libopenvizsla/actions/runs/3284338863

**Comment by desowin** [comment]
`Debug package for Windows Win32` and `Debug package for Windows x64` complains about missing `VCRUNTIME140D.dll` and `ucrtbased.dll` but I believe it is expected on systems that do not have Visual Studio installed.

`Release package for Windows Win32` and `Release package for Windows x64` work fine when the `bin` directory contents are copied to Wireshark Personal Extcap path (Help->About Wireshark->Folders). Actual capture works fine when libusbK driver for OpenVizsla is installed using Zadig.

**Comment by matwey** [comment]
Thanks. It seems that I've finally figured out how to create windows bundles with cmake :-D
