### ISSUE TITLE
Force FPGA firmware download?

### ISSUE THREAD

**Issue by desowin** [matwey/libopenvizsla#13]
Currently the `ov_open()` will skip firmware download based on the `PORTB_INIT_BIT` and `PORTB_DONE_BIT` state. While this is ok with pretty much the single firmware package floating around, it seems to me that it is prone to problems when (and if) we get multiple firmwares (e.g. with the NAK filter built in and/or streaming pcap directly).

The actual firmware download is pretty fast and I think we could just force FPGA reset and programming on every startup - that way the executable will always work with its bundled firmware package regardless of what other packages/versions might be there.

**Comment by matwey** [comment]
You are right. This behavior has been taken from the origin OpenVizsla software. But the most important issue here is that we have the register mapping and the firmware, and we just believe that the uploaded firmware is consistent with our register mapping. There is no way to check it in runtime except force-load firmware.

I am not sure however, what implications of firmware loading on FPGA chip itself. Maybe number of life-time uploads are limited somehow.

**Comment by desowin** [comment]
> I am not sure however, what implications of firmware loading on FPGA chip itself. Maybe number of life-time uploads are limited somehow.

Xilinx Spartan-6 Family Overview states "Spartan-6 FPGAs store the customized configuration data in SRAM-type internal latches. The number of configuration bits is between 3 Mb and 33 Mb depending on device size and user-design implementation options. The configuration storage is volatile and must be reloaded whenever the FPGA is powered up. This storage can also be reloaded at any time by pulling the PROGRAM_B pin Low."

SRAM memories generally don't have reprogram limits. In OpenVizsla, we are not storing the FPGA configuration (firmware) in any non-volatile memory and instead we simply download it with host software.

**Comment by matwey** [comment]
Fixed in 8194ac6a936e594baf6a7800a2030ceab381cd44
