### ISSUE TITLE
Migrate appveyor mingw environments to vcpkg

### ISSUE THREAD

**Issue by matwey** [matwey/libopenvizsla#19]
mingw triplets are supported in vcpkg currently.
However, not all dependencies are installable for mingw triplets yet.

**Comment by matwey** [comment]
https://github.com/microsoft/vcpkg/issues/9751

**Comment by sfhacker** [comment]
Any news/update on this open and long standing issue?

**Comment by matwey** [comment]
Some dependencies still cannot be installed through vcpkg.

**Comment by sfhacker** [comment]
> Some dependencies still cannot be installed through vcpkg.

For example?
This open issue is several months old!
Perhaps I can assist with those dependencies.

**Comment by matwey** [comment]
It would be great.

Currently, `libusb` build is failed: https://github.com/microsoft/vcpkg/issues/9751

Also, look at https://github.com/matwey/libopenvizsla/commit/8b5ba5f637dfe8c65aa5845e01348836b5ccb533 for the reference.

*Upd:* Also, appveyor provides out-of-date `vcpkg`, and recent version cannot be rebuilt with mingw.

**Comment by sfhacker** [comment]
libusb is the only missing dependency?

We do not use vcpkg at all. We build large and complex projects on a regular basis without the need of vcpkg (there are over 1,000 open issues!!!).

Are there any Windows binaries available for download? If so, can you provide a link?

**Comment by matwey** [comment]
I am not sure, I was stuck at `libusb`.

`vcpkg` is used for Visual Studio build, while `mingw` build uses msys binary packages now. So it would be great to handle them uniformly.

If you just need prebuild `libopenvizsla` binaries, then it is another issue. The build artifacts can be uploaded to GitHub releases from Appveyor CI.

**Comment by sfhacker** [comment]
How much experience do you have building projects from source on Windows?

Just built master branch from source on Windows 10 x64 with no issues at all.

![image](https://user-images.githubusercontent.com/25817529/96918398-f4b55680-14f5-11eb-8f3b-4cad618f1ef3.png)

![image](https://user-images.githubusercontent.com/25817529/96918411-fb43ce00-14f5-11eb-99ab-827e62344835.png)

This open issue is like 8 months old!
Can you post here the errors you get when trying to build this project from source?

Cheers.

**Comment by desowin** [comment]
@sfhacker can you build statically linked Windows binaries as well?

**Comment by matwey** [comment]
> How much experience do you have building projects from source on Windows?
> 
> Just built master branch from source on Windows 10 x64 with no issues at all.

Exactly like it is happening in CI now: https://ci.appveyor.com/project/matwey/libopenvizsla/branch/master

> 
> ![image](https://user-images.githubusercontent.com/25817529/96918398-f4b55680-14f5-11eb-8f3b-4cad618f1ef3.png)
> 
> ![image](https://user-images.githubusercontent.com/25817529/96918411-fb43ce00-14f5-11eb-99ab-827e62344835.png)
> 
> This open issue is like 8 months old!

So what is the problem with this particular issue for you? It is not about mingw, it is about vcpkg.

> Can you post here the errors you get when trying to build this project from source?
> 
> Cheers.

**Comment by sfhacker** [comment]
> can you build statically linked Windows binaries as well?

I can build both (static & dynamic).
Many many many projects on GitHub provide packages or binaries to their users.
I wonder why this one doesn't.

**Comment by matwey** [comment]
We don't use AppVeyor anymore.
