### ISSUE TITLE
Do not force static check

### ISSUE THREAD

**Issue by dogtopus** [matwey/libopenvizsla#23]
On distros such as Arch installing check might not install the static library. Building on those distros will fail because of that.

**Comment by matwey** [comment]
Hi @dogtopus

Thank you for the report. Frankly speaking, I have not understood it completely. Do you mean that you have build issues at Arch Linux? If so, could you guide me how to reproduce it?

I've tested the build on Ubuntu (where is only static variant of `check` library) and on openSUSE (where is only shared variant of `check`). Both work fine for me.

**Comment by dogtopus** [comment]
Yes there was a build error.

After `sudo pacman -S gperf check`, then run `mkdir build && cd build && cmake -GNinja ..` (using Makefile gives the same result) and:

```
$ cmake -GNinja ..
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3") 
-- Found LibUSB1: usb-1.0 (found version "1.0.23") 
-- Found LibFTDI1: ftdi1;usb-1.0 (found version "1.4") 
-- Found LibZip: zip (found suitable version "1.6.1", minimum required is "1.0") 
CMake Error at /usr/lib64/cmake/check/check-targets.cmake:96 (message):
  The imported target "Check::check" references the file

     "/usr/lib/libcheck.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib64/cmake/check/check-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib64/cmake/check/check-config.cmake:36 (include)
  CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
```

The cmake library for check seems to be shipped with the `check` package. Currently the packaged version is `0.15.2`.

**Comment by matwey** [comment]
Now I see the same. Thank you. Unfortunately, It seems to be more complex issue than it initially looks like. The failure occurs at 
`find_package(Check CONFIG NAMES Check check)` before any target is actually used. I need some time to explore how it is supposed to work.

**Comment by matwey** [comment]
@dogtopus

Could you show where are the Arch Linux `check` package sources?

**Comment by dogtopus** [comment]
If you mean the packaging script: https://github.com/archlinux/svntogit-packages/tree/packages/check/trunk

It looks like it just downloads and installs check from github without any distro-specific stuff.

**Comment by matwey** [comment]
Related issue: https://bugs.archlinux.org/task/68076

**Comment by matwey** [comment]
@dogtopus could you please retry with updated package `check 0.15.2-2`? The first part of the issue seems to be resolved: `find_package()` doesn't break everything anymore.

**Comment by dogtopus** [comment]
Just tried it. Seems to work.

**Comment by matwey** [comment]
Great. Then we can move to the second phase. You are right that `Check::sharedCheck` target should be preferred over `Check::check`.

**Comment by matwey** [comment]
@dogtopus could you please try #24 ?

**Comment by dogtopus** [comment]
It works well for me.

**Comment by matwey** [comment]
Thank you.
